{"abstract":[{"text":"Private declaration of a method starting the ","type":"text"},{"type":"codeVoice","code":"edgeEngine"},{"text":" instance. ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"For internal mimik use."}]}],"identifier":{"url":"doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine\/Edge\/start(with:nodeId:nodeName:license:workingDirectory:startupParameters:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/edgeengine\/edge\/start(with:nodeid:nodename:license:workingdirectory:startupparameters:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/edgeengine\/edge\/start(with:nodeid:nodename:license:workingdirectory:startupparameters:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine","doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine\/Edge"]]},"metadata":{"modules":[{"name":"EdgeEngine"}],"symbolKind":"method","externalID":"c:objc(cs)Edge(im)startWith:nodeId:nodeName:licenseString:workingDirectory:startupParameters:","navigatorTitle":[{"text":"startWith:nodeId:nodeName:licenseString:workingDirectory:startupParameters:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"nodeId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"nodeName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"license"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"workingDirectory","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"text":"startupParameters","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]!) -> ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"}],"role":"symbol","title":"start(with:nodeId:nodeName:license:workingDirectory:startupParameters:)","roleHeading":"Instance Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"port"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"nodeId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"nodeName"},{"kind":"text","text":" "},{"text":"name","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"license"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"workingDirectory"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"startupParameters"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!) -> ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"]}]},{"parameters":[{"name":"port","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"code":"Port","type":"codeVoice"},{"type":"text","text":" number to host the "},{"code":"edgeEngine","type":"codeVoice"},{"text":" instance on, usually ","type":"text"},{"type":"codeVoice","code":"8083"},{"text":" unless changed.","type":"text"}]}]},{"name":"nodeId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"Node"},{"type":"text","text":" (device) identifier."}]}]},{"name":"name","content":[{"inlineContent":[{"type":"text","text":""},{"code":"Node","type":"codeVoice"},{"type":"text","text":" (device) name visible to other nodes (devices) on the network."}],"type":"paragraph"}]},{"name":"license","content":[{"inlineContent":[{"type":"text","text":"License and configuration for "},{"code":"edgeEngine","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}]},{"name":"workingDirectory","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Main file directory where "},{"type":"codeVoice","code":"edgeEngine"},{"text":" stores its configuration files, including the edge microservice containers and their data.","type":"text"}]}]},{"name":"startupParameters","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Custom "},{"code":"edgeEngine","type":"codeVoice"},{"text":" startup parameters.","type":"text"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"style":"note","type":"aside","name":"Note","content":[{"inlineContent":[{"text":"For more information about the edgeEngine platform see mimik ","type":"text"},{"isActive":true,"identifier":"https:\/\/devdocs.mimik.com\/introduction","type":"reference"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Developers ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"should not use this class directly"}]},{"type":"text","text":", instead the "},{"code":"EdgeCore","type":"codeVoice"},{"text":" client library ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/mimikgit.github.io\/cocoapod-EdgeCore\/documentation\/edgecore"},{"text":" should be used.","type":"text"}],"type":"paragraph"}],"name":"Warning","type":"aside","style":"warning"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"https://devdocs.mimik.com/introduction":{"title":"DevDocs","type":"link","url":"https:\/\/devdocs.mimik.com\/introduction","identifier":"https:\/\/devdocs.mimik.com\/introduction","titleInlineContent":[{"text":"DevDocs","type":"text"}]},"doc://com.mimik.cocoapod.EdgeEngine/documentation/EdgeEngine/Edge":{"navigatorTitle":[{"text":"Edge","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Edge","kind":"identifier"}],"abstract":[{"text":"Private declaration of ","type":"text"},{"code":"Edge","type":"codeVoice"},{"text":" platform class. ","type":"text"},{"inlineContent":[{"text":"For internal mimik use.","type":"text"}],"type":"strong"}],"title":"Edge","type":"topic","role":"symbol","identifier":"doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine\/Edge","url":"\/documentation\/edgeengine\/edge"},"doc://com.mimik.cocoapod.EdgeEngine/documentation/EdgeEngine":{"url":"\/documentation\/edgeengine","abstract":[{"type":"text","text":"mimik Client Library for iOS provides a programmatic way to work with the edgeEngine Runtime to access information about the mobile device on which the application is running."}],"role":"collection","type":"topic","identifier":"doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine","kind":"symbol","title":"EdgeEngine"},"https://mimikgit.github.io/cocoapod-EdgeCore/documentation/edgecore":{"titleInlineContent":[{"text":"API","type":"text"}],"title":"API","type":"link","identifier":"https:\/\/mimikgit.github.io\/cocoapod-EdgeCore\/documentation\/edgecore","url":"https:\/\/mimikgit.github.io\/cocoapod-EdgeCore\/documentation\/edgecore"},"doc://com.mimik.cocoapod.EdgeEngine/documentation/EdgeEngine/Edge/start(with:nodeId:nodeName:license:workingDirectory:startupParameters:)":{"url":"\/documentation\/edgeengine\/edge\/start(with:nodeid:nodename:license:workingdirectory:startupparameters:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"nodeId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"nodeName"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"text":"license","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"text":"workingDirectory","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"startupParameters"},{"text":": [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]!) -> ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"startWith:nodeId:nodeName:licenseString:workingDirectory:startupParameters:"}],"title":"start(with:nodeId:nodeName:license:workingDirectory:startupParameters:)","kind":"symbol","identifier":"doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine\/Edge\/start(with:nodeId:nodeName:license:workingDirectory:startupParameters:)","abstract":[{"text":"Private declaration of a method starting the ","type":"text"},{"code":"edgeEngine","type":"codeVoice"},{"text":" instance. ","type":"text"},{"inlineContent":[{"text":"For internal mimik use.","type":"text"}],"type":"strong"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"startWith:nodeId:nodeName:licenseString:workingDirectory:startupParameters:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"startWith:nodeId:nodeName:licenseString:workingDirectory:startupParameters:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"text":"startWith:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:I","text":"int","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"port","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"nodeId:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"nodeId"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nodeName:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"name","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"licenseString:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"license","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"workingDirectory:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"workingDirectory"},{"text":" ","kind":"text"},{"text":"startupParameters:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"startupParameters"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"Edge","path":"\/references\/doc:~1~1com.mimik.cocoapod.EdgeEngine~1documentation~1EdgeEngine~1Edge\/title"},{"path":"\/references\/doc:~1~1com.mimik.cocoapod.EdgeEngine~1documentation~1EdgeEngine~1Edge\/fragments","value":[{"kind":"identifier","text":"Edge"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mimik.cocoapod.EdgeEngine~1documentation~1EdgeEngine~1Edge~1start(with:nodeId:nodeName:license:workingDirectory:startupParameters:)\/title","value":"startWith:nodeId:nodeName:licenseString:workingDirectory:startupParameters:"},{"path":"\/references\/doc:~1~1com.mimik.cocoapod.EdgeEngine~1documentation~1EdgeEngine~1Edge~1start(with:nodeId:nodeName:license:workingDirectory:startupParameters:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"startWith:nodeId:nodeName:licenseString:workingDirectory:startupParameters:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}