{"abstract":[{"text":"mimik Client Library provides a programmatic way to work with the edgeEngine Runtime to access information about the mobile device on which the application is running.","type":"text"}],"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"content","content":[{"level":2,"text":"Overview","anchor":"Overview","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The purpose of the mimik Client Library is to provide a programmatic way to work with the edgeEngine Runtime to access information about the mobile device on which the application is running, as well as mobile devices running within a cluster of mobile devices that are hosting the edgeEngine Runtime. Also, to allow developers to use edge microservices running within a particular cluster.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"By leveraging the Core component of the mimik Client Library, developers can build applications compatible with the edgeEngine Runtime. This not only harnesses the strength of edge computing but also provides an inherent flexibility in its paradigm."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Additionally, this component provides utility APIs that help developers with core operations such as Authentication, edgeEngine Runtime Setup, deployment of edge microservices and handling of Network calls."}]},{"inlineContent":[{"text":"Furthermore, the mimik Client Library Engine component provides additional edgeEngine Runtime utility APIs, as well as vendoring the actual edgeEngine Runtime binary into the iOS project.","type":"text"}],"type":"paragraph"},{"text":"Supported Platforms, Targets","anchor":"Supported-Platforms-Targets","type":"heading","level":2},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"code":"iOS Devices running iOS 15+","type":"codeVoice"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"code":"iOS Simulators running iOS 15+","type":"codeVoice"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"iOS Mac Catalyst running macOS 12.0"}]}]}]},{"text":"Requirements","anchor":"Requirements","type":"heading","level":2},{"code":["iOS 15.0+"],"syntax":null,"type":"codeListing"},{"text":"Installation","level":2,"type":"heading","anchor":"Installation"},{"type":"paragraph","inlineContent":[{"text":"To install it, simply add the following lines to your Podfile:","type":"text"}]},{"code":["platform :ios, '15.0'","source 'https:\/\/github.com\/CocoaPods\/Specs.git'","source 'https:\/\/github.com\/mimikgit\/cocoapod-edge-specs.git'","","use_frameworks!","inhibit_all_warnings!","","def mimik","  pod 'EdgeCore'","  pod 'EdgeEngine'","end","","target '{target}' do","  mimik()","end","","post_install do |installer|","  installer.pods_project.targets.each do |target|","    target.build_configurations.each do |config|","      config.build_settings['ENABLE_BITCODE'] = 'NO'","      config.build_settings['VALID_ARCHS'] = '$(ARCHS_STANDARD_64_BIT)'","      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'","      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'","    end","  end","end"],"syntax":"swift","type":"codeListing"},{"text":"Tutorials","type":"heading","anchor":"Tutorials","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"After installation, try the following tutorials:"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"https:\/\/devdocs.mimik.com\/tutorials\/11-index","isActive":true}]}]},{"content":[{"inlineContent":[{"identifier":"https:\/\/devdocs.mimik.com\/tutorials\/12-index","isActive":true,"type":"reference"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"https:\/\/devdocs.mimik.com\/tutorials\/13-index","type":"reference","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"https:\/\/devdocs.mimik.com\/tutorials\/10-index"}]}]}],"type":"unorderedList"},{"level":2,"text":"Online API Reference Documentation","type":"heading","anchor":"Online-API-Reference-Documentation"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The full API reference documentation can be found at "},{"identifier":"https:\/\/mimikgit.github.io\/cocoapod-EdgeCore\/documentation\/edgecore","isActive":true,"type":"reference"},{"type":"text","text":"."}]},{"inlineContent":[{"type":"text","text":"Alternatively the Xcode docc archive file can be downloaded as a "},{"type":"reference","isActive":true,"identifier":"https:\/\/github.com\/mimikgit\/cocoapod-EdgeCore\/tree\/main\/EdgeCore.doccarchive.zip"},{"type":"text","text":" and opened locally."}],"type":"paragraph"},{"level":2,"anchor":"mimik-client-libraries","text":"mimik client libraries","type":"heading"},{"inlineContent":[{"type":"text","text":"Don’t forget to checkout all mimik client libraries "},{"type":"reference","identifier":"https:\/\/github.com\/search?q=cocoapod-Edge","isActive":true}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Umbrella cocoapods:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"https:\/\/github.com\/mimikgit\/cocoapod-EdgeClientLibrary"}]}]},{"content":[{"inlineContent":[{"identifier":"https:\/\/github.com\/mimikgit\/cocoapod-EdgeClientLibraryTrial","isActive":true,"type":"reference"}],"type":"paragraph"}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Individual cocoapods:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"https:\/\/github.com\/mimikgit\/cocoapod-EdgeCore","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"https:\/\/github.com\/mimikgit\/cocoapod-EdgeEngine","isActive":true,"type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"https:\/\/github.com\/mimikgit\/cocoapod-EdgeEngineDeveloper","isActive":true,"type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"https:\/\/github.com\/mimikgit\/cocoapod-EdgeUser","type":"reference","isActive":true}]}]}]},{"type":"heading","text":"Author","anchor":"Author","level":2},{"inlineContent":[{"text":"mimik","type":"text"}],"type":"paragraph"},{"code":["https:\/\/github.com\/mimikgit\/cocoapod-EdgeCore"],"syntax":null,"type":"codeListing"},{"text":"License","level":2,"type":"heading","anchor":"License"},{"type":"paragraph","inlineContent":[{"text":"The aforementioned mimik client and service libraries are available under the MIT license. See the LICENSE file for more information.","type":"text"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[[]]},"topicSections":[{"identifiers":["doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine\/Edge"],"title":"Classes"},{"identifiers":["doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine\/EdgeCore"],"title":"Extended Modules"}],"identifier":{"url":"doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/edgeengine"]},{"paths":["\/documentation\/edgeengine"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"EdgeEngine"}],"symbolKind":"module","color":{"standardColorIdentifier":"orange"},"role":"collection","title":"EdgeEngine","externalID":"EdgeEngine","roleHeading":"Framework"},"references":{"https://mimikgit.github.io/cocoapod-EdgeCore/documentation/edgecore":{"identifier":"https:\/\/mimikgit.github.io\/cocoapod-EdgeCore\/documentation\/edgecore","type":"link","titleInlineContent":[{"text":"GitHub Pages","type":"text"}],"title":"GitHub Pages","url":"https:\/\/mimikgit.github.io\/cocoapod-EdgeCore\/documentation\/edgecore"},"doc://com.mimik.cocoapod.EdgeEngine/documentation/EdgeEngine":{"identifier":"doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine","type":"topic","kind":"symbol","title":"EdgeEngine","url":"\/documentation\/edgeengine","role":"collection","abstract":[{"type":"text","text":"mimik Client Library provides a programmatic way to work with the edgeEngine Runtime to access information about the mobile device on which the application is running."}]},"https://devdocs.mimik.com/tutorials/13-index":{"type":"link","identifier":"https:\/\/devdocs.mimik.com\/tutorials\/13-index","url":"https:\/\/devdocs.mimik.com\/tutorials\/13-index","titleInlineContent":[{"text":"Working with edge microservices in an iOS project","type":"text"}],"title":"Working with edge microservices in an iOS project"},"https://github.com/mimikgit/cocoapod-EdgeCore":{"identifier":"https:\/\/github.com\/mimikgit\/cocoapod-EdgeCore","type":"link","titleInlineContent":[{"text":"EdgeCore","type":"text"}],"title":"EdgeCore","url":"https:\/\/github.com\/mimikgit\/cocoapod-EdgeCore"},"https://github.com/mimikgit/cocoapod-EdgeEngine":{"type":"link","identifier":"https:\/\/github.com\/mimikgit\/cocoapod-EdgeEngine","url":"https:\/\/github.com\/mimikgit\/cocoapod-EdgeEngine","titleInlineContent":[{"text":"EdgeEngine","type":"text"}],"title":"EdgeEngine"},"https://devdocs.mimik.com/tutorials/10-index":{"identifier":"https:\/\/devdocs.mimik.com\/tutorials\/10-index","type":"link","titleInlineContent":[{"text":"Creating a Simple iOS Application that Uses an edge microservice","type":"text"}],"title":"Creating a Simple iOS Application that Uses an edge microservice","url":"https:\/\/devdocs.mimik.com\/tutorials\/10-index"},"https://github.com/mimikgit/cocoapod-EdgeClientLibrary":{"type":"link","identifier":"https:\/\/github.com\/mimikgit\/cocoapod-EdgeClientLibrary","url":"https:\/\/github.com\/mimikgit\/cocoapod-EdgeClientLibrary","titleInlineContent":[{"text":"EdgeClientLibrary (Core + Engine)","type":"text"}],"title":"EdgeClientLibrary (Core + Engine)"},"https://github.com/mimikgit/cocoapod-EdgeEngineDeveloper":{"identifier":"https:\/\/github.com\/mimikgit\/cocoapod-EdgeEngineDeveloper","type":"link","titleInlineContent":[{"text":"EdgeEngineDeveloper","type":"text"}],"title":"EdgeEngineDeveloper","url":"https:\/\/github.com\/mimikgit\/cocoapod-EdgeEngineDeveloper"},"https://github.com/search?q=cocoapod-Edge":{"type":"link","identifier":"https:\/\/github.com\/search?q=cocoapod-Edge","url":"https:\/\/github.com\/search?q=cocoapod-Edge","titleInlineContent":[{"text":"available on Github","type":"text"}],"title":"available on Github"},"https://devdocs.mimik.com/tutorials/11-index":{"identifier":"https:\/\/devdocs.mimik.com\/tutorials\/11-index","type":"link","titleInlineContent":[{"text":"Integrating the mimik Client Library into an iOS project","type":"text"}],"title":"Integrating the mimik Client Library into an iOS project","url":"https:\/\/devdocs.mimik.com\/tutorials\/11-index"},"https://github.com/mimikgit/cocoapod-EdgeUser":{"titleInlineContent":[{"type":"text","text":"EdgeUser"}],"url":"https:\/\/github.com\/mimikgit\/cocoapod-EdgeUser","title":"EdgeUser","type":"link","identifier":"https:\/\/github.com\/mimikgit\/cocoapod-EdgeUser"},"doc://com.mimik.cocoapod.EdgeEngine/documentation/EdgeEngine/Edge":{"identifier":"doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine\/Edge","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Edge","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Edge"}],"url":"\/documentation\/edgeengine\/edge","title":"Edge","abstract":[{"type":"text","text":"Private declaration of "},{"code":"edgeEngine","type":"codeVoice"},{"text":" platform class. ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"For internal mimik use."}]}]},"https://devdocs.mimik.com/tutorials/12-index":{"titleInlineContent":[{"type":"text","text":"Working with edgeEngine in an iOS project"}],"type":"link","identifier":"https:\/\/devdocs.mimik.com\/tutorials\/12-index","url":"https:\/\/devdocs.mimik.com\/tutorials\/12-index","title":"Working with edgeEngine in an iOS project"},"https://github.com/mimikgit/cocoapod-EdgeClientLibraryTrial":{"titleInlineContent":[{"text":"EdgeClientLibraryTrial (Core + EngineTrial)","type":"text"}],"type":"link","title":"EdgeClientLibraryTrial (Core + EngineTrial)","identifier":"https:\/\/github.com\/mimikgit\/cocoapod-EdgeClientLibraryTrial","url":"https:\/\/github.com\/mimikgit\/cocoapod-EdgeClientLibraryTrial"},"doc://com.mimik.cocoapod.EdgeEngine/documentation/EdgeEngine/EdgeCore":{"kind":"symbol","url":"\/documentation\/edgeengine\/edgecore","type":"topic","role":"collection","abstract":[],"identifier":"doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine\/EdgeCore","title":"EdgeCore"},"https://github.com/mimikgit/cocoapod-EdgeCore/tree/main/EdgeCore.doccarchive.zip":{"titleInlineContent":[{"type":"text","text":"zip"}],"type":"link","identifier":"https:\/\/github.com\/mimikgit\/cocoapod-EdgeCore\/tree\/main\/EdgeCore.doccarchive.zip","url":"https:\/\/github.com\/mimikgit\/cocoapod-EdgeCore\/tree\/main\/EdgeCore.doccarchive.zip","title":"zip"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine\/Edge"]}]},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/references\/doc:~1~1com.mimik.cocoapod.EdgeEngine~1documentation~1EdgeEngine~1Edge\/title","value":"Edge","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"Edge"}],"path":"\/references\/doc:~1~1com.mimik.cocoapod.EdgeEngine~1documentation~1EdgeEngine~1Edge\/fragments"}]}]}